name: goodman_lamps

dependencies:
  - python=3.7
  - qt
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - pyqt5
      - ccdproc
      - coveralls
      - m2r
      - sphinx
      - sphinx_rtd_theme
      - sphinxcontrib.napoleon
      - goodman_pipeline
